### ISSUE TITLE
Error variables de css usandolo en los otros archivos css con los selectores de clase

### ISSUE THREAD

**Issue by senixcode** [rogeliosamuel621/Thrillo#18]
``` css
/*styles/vars.css */
:root {
    --primary: "#2F80ED";
    --secundary: "#DAE4FD";
    --color-dark: "#000000";
    --color-white: #FFFFFF;
    --bg-color-white: #eeeeee
}
/*styles/app.css*/
body {
    margin: 0;
    font-family: 'Poppins', sans-serif;
   /*funciona*/
    background-color: var(--bg-color-white);
}
/*ejemplo en otro archivo*/
.custom {
  /* no funciona */
    background-color: var(--primary);
 /*funciona*/
    background-color: #fff;
}
```
